In [3]:
import numpy as np

In [4]:
dims = [2,4,10,3,1]

In [27]:
np.random.seed()
weights = list()
for i in range(len(dims)-1):
    weight_array = np.random.randn(dims[i],dims[i+1])
    print(np.shape(weight_array))
    #print(np.shape(weight_array[0,:]))
    weight_array[0,:] = np.random.randn(dims[i+1]) * 0.01
    weights.append(weight_array)

print(len(weight_array),len(dims))

(2, 4)
(4, 10)
(10, 3)
(3, 1)
3 5


In [26]:
network_input_size = 2
layer_output_sizes = [4,10,3,1]

layers = []

input_size = network_input_size
for output_size in layer_output_sizes:
    W = np.random.randn(input_size, output_size)
    b = np.random.randn(output_size)
    layers.append((W, b))
    print(np.shape(W))
    input_size = output_size

    #(out,in)


(2, 4)
(4, 10)
(10, 3)
(3, 1)


In [14]:
layers

[(array([[ 1.84703376,  0.78622065],
         [-0.00282898, -0.74444692],
         [-0.67894849, -1.37740531],
         [ 0.74730963,  0.03855254]]),
  array([-0.27434914, -0.5254545 ,  0.47471253,  0.95676817])),
 (array([[-0.59608933,  0.35742609, -0.41357614,  1.31990616],
         [-2.67240069,  0.71277565,  0.67803209, -1.13865303],
         [-0.80835154, -1.47108311,  0.30513981,  0.19829524],
         [-0.3796339 ,  1.76851372, -0.08325394, -2.49110996],
         [ 0.37840072, -0.25343602,  0.83203739,  1.38070906],
         [-0.82067544,  0.03043475,  0.98029691, -0.68545153],
         [-0.15782218,  1.12414253,  1.31779229, -1.13994652],
         [-1.20929815,  0.41803949,  0.409575  , -0.99098667],
         [-0.52662106, -0.8754896 , -0.43844117,  0.38727919],
         [-1.04290943,  0.17673302,  2.11489557,  0.46913279]]),
  array([-0.11065468,  0.16468475, -1.85125736, -0.05107527,  1.71859734,
          0.6692027 , -0.62746308,  0.75599899,  1.75137357, -0.17674175])),
 (a